/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

import skyScene from "../assets/3d/free_-_skybox_anime_sky.glb";

const Sky = () => {
    const sky = useGLTF(skyScene);
    return (
        <mesh  scale={0.1}>
            <primitive object={sky.scene} />
        </mesh>
    )
}

export default Sky;



/**
 * import { useRef,useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame ,useThree } from '@react-three/fiber'
import{a} from '@react-spring/three'

import skyScene from "../assets/3d/sky.glb";

const Sky=(props)=> {
    const skyRef=useRef()
  const { nodes, materials } = useGLTF(skyScene)
  return (
    <a.group ref={skyRef}{...props}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Sphere__0.geometry}
          material={materials['Scene_-_Root']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={500}
        />
      </group>
    </a.group>
  )
}

export default Sky;
 */
